# Generated by Django 3.1.5 on 2021-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color_turn',
            field=models.CharField(default='w', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='position',
            field=models.CharField(default='3p4/8/8/8/8/8/8/P1P1P1P1', max_length=200),
        ),
    ]
