# Generated by Django 3.1.5 on 2021-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210109_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='second_player',
            field=models.CharField(default='', max_length=200),
        ),
    ]
