# Generated by Django 3.1.5 on 2021-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210117_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator_color',
            field=models.CharField(default='b', max_length=2),
            preserve_default=False,
        ),
    ]
