# Generated by Django 3.1.5 on 2021-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_room_creator_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='color_turn',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator_color',
            field=models.CharField(max_length=5),
        ),
    ]
